### ISSUE TITLE
Incorrect allocation-error handling

### ISSUE THREAD

**Issue by szsam** [stateos/common#1]
https://github.com/stateos/common/blob/b3abc3a8cecc235e05d69eab2d144ab480c5865b/stateos/kernel/inc/osbarrier.h#L353-L354
If `new T` fails for some type `T`, it throws a `std::bad_alloc` exception. The `new` operator cannot return null.

FYI, `new(std::nothrow) T` returns a null pointer when allocation fails.

**Comment by rajszym** [comment]
Thanks for reporting the problem. I'll take a look at it right now.

**Comment by rajszym** [comment]
Reported bug has been fixed

**Comment by szsam** [comment]
Fixed in 881e328

**Comment by Machiry** [comment]
Hello @rajszym ,

My name is Aravind Machiry, Assistant Professor at Purdue's ECE Department.

Thank you for considering this pull request. This pull request was the result of our on-going research work (along with @szsam) to improve the security of open-source embedded projects.

In addition to scanning codebases with CodeQL, we are also doing a short (~4 minutes) survey to understand the use of static analysis tools like `gcc -Wall` and CodeQL in embedded software projects.

It would greatly benefit our research if you could fill this anonymous survey: https://purdue.ca1.qualtrics.com/jfe/form/SV_0OnXfr5plPe1QCa

Thank you,
Aravind
